### ISSUE TITLE
ImportError: No module named 'accounting'

### ISSUE THREAD

**Issue by jlebunetel** [laboiteproject/laboite-erp#5]
Following the [Django tutorial 2](https://docs.djangoproject.com/fr/1.10/intro/tutorial02/), I created some models, added _accounting_ references in the files _urls.py_ and _settings.py_.
When I run `python manage.py runserver` it return the following issue:
`ImportError: No module named 'accounting'`
It seem I have a problem in path, but where ? virtualenv ? django ? python ?

**Comment by vrialland** [comment]
@jlebunetel : I think the "accounting" app folder shouldn't be in the "laboite_erp" folder but at the root of the project. This way it loads properly.

**Comment by Natim** [comment]
It should be `laboite_erp.accounting`

**Comment by Natim** [comment]
> the "accounting" app folder shouldn't be in the "laboite_erp" folder

This is a good idea only if you want to reuse the accounting app between project. In that specific case we don't want to do that, more over we don't want to polute the Python namespace with the accounting name.

**Comment by jlebunetel** [comment]
@vrialland : I tried your way, it works ! Thanks ! But, I will follow @Natim solution.
I changed `accounting.urls` to  `laboite_erp.accounting.urls` in `\laboite_erp\urls.py`. It works.
But, when I try to add a reference to the configuration class in the INSTALLED_APPS setting in `\laboite_erp\settings.py`, neither `'accounting.apps.AccountingConfig',` nor `'laboite_erp.accounting.apps.AccountingConfig',` works. It shows the same error message : `ImportError: No module named 'accounting'`

**Comment by Natim** [comment]
Make sure `laboite_erp/` contains a `__init__.py` file

**Comment by jlebunetel** [comment]
It's an empty file, but it exist.
In `laboite_erp/accounting` too.

**Comment by jlebunetel** [comment]
The error message does not appear when I change `'laboite_erp.accounting.apps.AccountingConfig',` to `'laboite_erp.accounting',`. It seams the module `accounting` is imported.
But isn't it necessary to add a reference to the `apps.AccountingConfig` before running `makemigrations` ?

**Comment by Natim** [comment]
I think the INSTALLED_APPS should only be `laboite_erp.accounting` and then you can define the default config in `accounting/__init__.py` cf https://docs.djangoproject.com/fr/1.10/ref/applications/#for-application-authors

**Comment by jlebunetel** [comment]
In the file `laboite_erp/accounting/apps.py`, I change `name = 'accounting'` to `name = 'laboite_erp.accounting'` and it solve the problem.
I can run `python manage.py makemigrations accounting` and `python manage.py migrate` and I can go on the tutorial ...
Thanks @Natim and @vrialland !
